eeprom: initialize size field
madisongh/tegra-eeprom-tool pull request #5
Opened 2022-09-18 21:00 UTC by kekiefer

The size field was previously unused in cboot checks for eeprom validity. With NVIDIA's edk2-firmware, it uses this size field for a sanity check. Initialize this field.

Signed-off-by: Kurt Kiefer <kurt.kiefer@arthrex.com>

2022-09-18 21:27 UTC, ichergui approved these changes
Thanks @kekiefer

2022-09-19 11:35 UTC, madisongh requested changes

2022-09-19 11:35 UTC, madisongh commented on eeprom.c
> +	rawdata->length = sizeof(*rawdata) - 1;
Could you use `htole16()` here, as I've done elsewhere for 16-bit fields?

Also, could you update the 'no longer used' comment on the `length` field at the top of the file, it's obviously wrong. :)

2022-10-02 11:49 UTC, madisongh commented
I've merged this manually with the modifications I mentioned above.  Thanks!

2022-10-02 11:49 UTC, closed without merging